# Generated by Django 5.1.6 on 2025-02-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repayment',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='repayment',
            name='reference',
            field=models.CharField(default='default-ref', max_length=255, unique=True),
        ),
    ]
