# Generated by Django 5.1.6 on 2025-03-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='campaign_logos/'),
        ),
    ]
