# Generated by Django 5.1.6 on 2025-03-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_defaulted',
            field=models.BooleanField(default=False),
        ),
    ]
